name: Mimi
on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          HOME_ID: ${{ secrets.HOME_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DEADMANSNITCH_ID: ${{ secrets.DEADMANSNITCH_ID }}
          PERSON_ID: ${{ secrets.PERSON_ID }}
        run: ./mimi.sh
